// <auto-generated />
using System;
using GHT.Domine.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace GHT.Domine.Migrations
{
    [DbContext(typeof(GHTContext))]
    partial class GHTContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.4")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("GHT.Core.Entities.Buys", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("ItemId")
                        .HasColumnType("int");

                    b.Property<DateTime>("dateBuy")
                        .HasColumnType("datetime2");

                    b.Property<int>("idItem")
                        .HasColumnType("int");

                    b.Property<int>("quantity")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.HasIndex("ItemId");

                    b.ToTable("Buys");
                });

            modelBuilder.Entity("GHT.Core.Entities.Items", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("nameItems")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("residue")
                        .HasColumnType("int");

                    b.Property<float>("unitValue")
                        .HasColumnType("real");

                    b.HasKey("id");

                    b.ToTable("Items");
                });

            modelBuilder.Entity("GHT.Core.Entities.Buys", b =>
                {
                    b.HasOne("GHT.Core.Entities.Items", "Items")
                        .WithMany()
                        .HasForeignKey("ItemId");

                    b.Navigation("Items");
                });
#pragma warning restore 612, 618
        }
    }
}
